# Generated by Django 4.1.4 on 2022-12-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_rename_almacenes_almacen_rename_productos_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='almacen',
            options={'verbose_name_plural': 'Almacenes'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name_plural': 'Stock'},
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='almacen',
            new_name='almacen_id',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='producto',
            new_name='producto_id',
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('producto_id', 'almacen_id')},
        ),
    ]
